---
 
- jenkins_job:
   config: "{{ lookup('file', 'files/template.xml') }}"
   name: java_pipeline 
   url: "http://127.0.0.1:8080"
   user: "{{ jenkins_user }}"
   password: "{{ jenkins_password }}"

